[package]
name = "learning"
version = "0.1.0"
authors = ["Lywnna"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.15"
